name: Check typos

on:
    # Runs on pushes targeting the default branch
    push:
        branches: ["main"]

    # Allows you to run this workflow manually from the Actions tab
    workflow_dispatch:

# Allow one concurrent deployment
concurrency:
    group: "typos"
    cancel-in-progress: true

jobs:
    typos:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v4
              with:
                  submodules: "true"
            - name: typos-action
              uses: crate-ci/typos@v1.29.0
